baseURL: 'https://michaelacheong.com/'
title: Michaela Cheong
languageCode: en-au
paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

pygmentsUseClasses: true
googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

permalinks:
  posts: '/:filename/'
  booksofbible: '/:title/'

params:
  env: production
  title: Michaela Cheong
  description: A digital garden that is morphing into a personal landing page.
  keywords:
    - Digital Garden
    - Blog
    - Portfolio
    - PaperMod
    - Christian
  author: Me
  images:
    - '<link or path of image for opengraph, twitter-cards>'
  DateFormat: 'Jan 2, 2006'
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hideMeta: false
  hideSearchMeta: true
  hideSummary: false
  showtoc: true
  tocopen: false
  CapitalizeListTitles: false
  fontheader: Avara_Bold
  fontbody: Times New Roman
  fontcode: Xanh Mono
  label:
    text: Home
    icon: apple-touch-icon.png
    iconHeight: 50
  profileMode:
    enabled: true
    title: Michaela's internet bay window
    subtitle: 'I follow Jesus. This is my digital garden that is morphing into a personal landing page. Read [Welcome to my digital garden](/welcome/) first.'
    imageUrl: img/meta/lol.jpg
    imageWidth: 120
    imageHeight: 120
    imageTitle: Site monogram
    buttons:
      - name: posts
        url: posts/
      - name: tags
        url: tags/
  socialIcons:
    - name: github
      url: 'https://github.com/vitamickey'
    - name: instagram
      url: 'https://www.instagram.com/michaelacheong/'
    - name: spotify
      url: 'https://open.spotify.com/user/mrshmllow_micky?si=70da848a98c84a3e'
    - name: pinterest
      url: 'https://pin.it/4IU6Skz'
  analytics:
    google:
      SiteVerificationTag: XYZabc
    bing:
      SiteVerificationTag: XYZabc
    yandex:
      SiteVerificationTag: XYZabc
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true
  editPost:
    URL: 'https://github.com/vitamickey/hugo-website/tree/main/content'
    Text: suggest edits on GitHub
    appendFilePath: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content
  assets:
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"
    safari_pinned_tab:  "/safari-pinned-tab.svg"
    disableFingerprinting: true


taxonomies:
  category: categories
  tag: tags
  series: series
  bookofbible: booksofbible

menu:
  main:
    - identifier: nowmenu
      name: now
      url: now/
      weight: 10
    - identifier: posts
      name: posts
      url: posts/
      weight: 20
    - identifier: bible
      name: bible
      url: booksofbible/
      weight: 30
    - identifier: tags
      name: tags
      url: tags/
      weight: 40
    - identifier: search
      name: search
      url: search/
      weight: 50

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
